[package]
name = "devilnput"
version = "0.2.0"
authors = ["anekos <anekos@snca.net>"]
license = "MIT OR Apache-2.0"

[dependencies]
argparse = "*"
uinput-sys = "0.1.5"
wraited-struct = "0.2.0"
evdev-rs = "0.1.0"
